export const AUTH_TOGGLE_DISPLAY_MODAL = 'AUTH_TOGGLE_DISPLAY_MODAL';
export const ENTRY_TOGGLE_DISPLAY_MODAL = 'ENTRY_TOGGLE_DISPLAY_MODAL';

export const AUTH_HIDE_DISPLAY_MODAL = 'AUTH_HIDE_DISPLAY_MODAL';
export const ENTRY_HIDE_DISPLAY_MODAL = 'ENTRY_HIDE_DISPLAY_MODAL';

export const UPDATE_AUTH_VALUE = 'UPDATE_AUTH_VALUE';
export const UPDATE_ENTRY_VALUE = 'UPDATE_ENTRY_VALUE';

export const TOGGLE_SHOW_GRAPH = 'TOGGLE_SHOW_GRAPH';
export const CHANGE_CURRENT_CHALLENGE = 'CHANGE_CURRENT_CHALLENGE';
