version: '2'

services:

  ###############################################
  #                    Server                   #
  ###############################################

  server:
    container_name: "inverted_chcharity_run_server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./server:/var/www/html
      - ./docker/files/:/var/www/sqlite
    user: "0"