export const AUTH_FETCH_STARTED = 'AUTH_FETCH_STARTED';
export const AUTH_FETCH_FINISHED = 'AUTH_FETCH_FINISHED';

export const AUTH_UPDATE_STARTED = 'AUTH_UPDATE_STARTED';
export const AUTH_UPDATE_FINISHED = 'AUTH_UPDATE_FINISHED';
export const AUTH_UPDATE_FAILED = 'AUTH_UPDATE_FAILED';
