export const ENTRY_FETCH_STARTED = 'ENTRY_FETCH_STARTED';
export const ENTRY_FETCH_FINISHED = 'ENTRY_FETCH_FINISHED';
export const ENTRY_FETCH_FAILED = 'ENTRY_FETCH_FAILED';

export const ENTRY_UPDATE_STARTED = 'ENTRY_UPDATE_STARTED';
export const ENTRY_UPDATE_FINISHED = 'ENTRY_UPDATE_FINISHED';
export const ENTRY_UPDATE_FAILED = 'ENTRY_UPDATE_FAILED';
